"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowLeft, Download, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { ComparisonResponse } from "@/types";

function ReportSection({ content }: { content: string }) {
  const sections = content.split(/^## /m).filter(Boolean);

  return (
    <div className="space-y-6">
      {sections.map((section, i) => {
        const newlineIdx = section.indexOf("\n");
        const heading = newlineIdx === -1 ? section : section.slice(0, newlineIdx);
        const body = newlineIdx === -1 ? "" : section.slice(newlineIdx + 1).trim();

        return (
          <div key={i} className="rounded-2xl border bg-white p-5 shadow-sm">
            <h2 className="text-base font-semibold text-gray-900 mb-2">{heading}</h2>
            <div className="text-sm text-gray-700 whitespace-pre-wrap leading-relaxed">
              {body}
            </div>
          </div>
        );
      })}
    </div>
  );
}

export default function ReportPage() {
  const [analysis, setAnalysis] = React.useState<string | null>(null);
  const [error, setError] = React.useState<string | null>(null);
  const [data, setData] = React.useState<ComparisonResponse | null>(null);

  React.useEffect(() => {
    const raw = localStorage.getItem("reportData");
    if (!raw) {
      setError("No comparison data found. Please run a comparison first.");
      return;
    }

    let parsed: ComparisonResponse;
    try {
      parsed = JSON.parse(raw) as ComparisonResponse;
    } catch {
      setError("Could not read comparison data.");
      return;
    }

    setData(parsed);

    fetch("/api/report/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        results: parsed.results,
        amount: parsed.amount,
        source_currency: parsed.source_currency,
        target_currency: parsed.target_currency,
      }),
    })
      .then((r) => r.json())
      .then((json: { analysis?: string; error?: string }) => {
        if (json.error) setError(json.error);
        else setAnalysis(json.analysis ?? null);
      })
      .catch(() => setError("Failed to generate report. Please try again."));
  }, []);

  function handlePrint() {
    window.print();
  }

  if (error) {
    return (
      <main className="min-h-screen bg-zinc-50 flex items-center justify-center px-4">
        <div className="text-center space-y-4">
          <p className="text-red-600 font-medium">{error}</p>
          <Button asChild variant="outline" className="rounded-xl">
            <Link href="/compare">Back to Compare</Link>
          </Button>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-zinc-50 px-4 py-10 sm:py-14 print:bg-white print:py-4">
      <div className="w-full max-w-2xl mx-auto space-y-6">

        {/* Header */}
        <div className="flex items-center justify-between print:hidden">
          <Button asChild variant="ghost" size="sm" className="gap-1.5 -ml-1">
            <Link href="/compare">
              <ArrowLeft className="h-4 w-4" />
              Back
            </Link>
          </Button>
          {analysis && (
            <Button
              variant="outline"
              size="sm"
              onClick={handlePrint}
              className="gap-1.5 rounded-xl"
            >
              <Download className="h-3.5 w-3.5" />
              Save / Print
            </Button>
          )}
        </div>

        {/* Title */}
        <div>
          <div className="inline-flex items-center gap-2 rounded-full bg-violet-100 text-violet-700 px-3 py-1 text-xs font-medium mb-3 print:hidden">
            Detailed Transfer Report
          </div>
          {data && (
            <h1 className="text-2xl font-bold text-gray-900">
              {data.source_currency} {data.amount.toLocaleString()} →{" "}
              {data.target_currency}
            </h1>
          )}
          <p className="text-sm text-muted-foreground mt-1">
            Generated by FibreTransfer
          </p>
        </div>

        {/* Loading */}
        {!analysis && !error && (
          <div className="flex flex-col items-center gap-3 py-16 text-muted-foreground">
            <Loader2 className="h-7 w-7 animate-spin text-violet-500" />
            <p className="text-sm">Generating your report…</p>
          </div>
        )}

        {/* Report content */}
        {analysis && <ReportSection content={analysis} />}

        {/* Footer */}
        {analysis && (
          <p className="text-center text-xs text-zinc-400 print:hidden">
            Want smart timing alerts for this corridor?{" "}
            <Link href="/subscribe" className="text-violet-600 hover:underline">
              Upgrade to Premium
            </Link>
          </p>
        )}
      </div>
    </main>
  );
}
